# 本地配置文件  需要在 .gitignore文件中进行忽略
# @author <a href="https://github.com/liliucc">程序员鱼皮</a>
# @from <a href="https://liucc.icu">编程导航知识星球</a>
server:
  port: 8120
# 对象存储
cos:
  client:
    accessKey: 'AKIDRlskOo0ykJhsoVyFNNCoCSVL2YrwoX3L'
    secretKey: 'A60DGJJDwSm6D6kAMK4d09JXYlyypW1I'
    region: 'ap-shanghai'
    bucket: 'yuzi-generator-1324070149'